<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsMonitorBLE_Setup</AssemblyName>
    <RootNamespace>WindowsMonitorBLE.Installer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\dist\payload.zip">
      <LogicalName>payload.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
